version: "3"

services:
  postgres-db:
    image: "postgres:11.10-alpine"
    restart: always
    ports:
      - "18008:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: "graphite"
      POSTGRES_USER: "graphite"
      POSTGRES_PASSWORD: "29345edd-334e-4aac-9a6d-24627401e205"
      PGDATA: /opt/graphite/storage/pgdb
    volumes:
      - "/opt/graphite/storage/pgdb:/opt/graphite/storage/pgdb"

  graphite-metrics:
    image: "omkar2020/graphite-fresh:pg"
    ports:
      - "80:80"
      - "18000:8125"
      - "18001:8126"
      - "18002:2003"
      - "18003:2004"
      - "18004:2023"
      - "18005:2024"
      - "18006:8080"
    depends_on:
      - "postgres-db"
    environment:
      GRAPHITE_POSTGRES_HOST: "postgres-db"
      GRAPHITE_POSTGRES_USER: "graphite"
      GRAPHITE_POSTGRES_PASSWORD: "29345edd-334e-4aac-9a6d-24627401e205"
    volumes:
      - "/opt/graphite/data/storage:/opt/graphite/storage"
      - "/var/log/msmonitoringsetup:/var/log"